# Follow: https://github.com/dependabot/dependabot-core/issues/2165 for multi-schedule
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    open-pull-requests-limit: 0
    schedule:
      interval: "daily"
      time: "05:00"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
