name: Publish

on:
  release:
    types: [created]

jobs:
  ci:
    uses: matthieubosquet/workflows/.github/workflows/node-ci.yml@v1.0.0
  publish:
    uses: matthieubosquet/workflows/.github/workflows/node-npm-publish.yml@v1.0.0
    needs: [ci]
    secrets:
      npm-token: ${{ secrets.NPM_TOKEN }}
